config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sindans
  resources :posts
  root 'posts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true
    mount_uploader :image, ImageUploader
end

app/models/sindan.rb
class Sindan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
      end
    
      def create
        post = Post.new(post_params)
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @post = Post.find(params[:id])
      end

      def edit
        @post = Post.find(params[:id])
      end

        def update
            post = Post.find(params[:id])
            
            post.user_id = current_user.id

            if post.update(post_params)
              redirect_to :action => "show", :id => post.id
            else
              redirect_to :action => "new"
            end
          end
 def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end

      private
      def post_params
        params.require(:post).permit(:name, :about,:image,:overall,:level)
      end
     #ここまで
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index
    end

    def new
        @sindan = Sindan.new
    end

    def show
        @sindan = Sindan.find_by(id: params[:id])
    end

    def create
        sindan = Sindan.new(sindan_params)
        if sindan.save
            flash[:notice] = "診断が完了しました"
            redirect_to sindan_path(sindan.id)
        else
            redirect_to :action => "new"
        end
    end
  
  private
    def sindan_params
        params.require(:sindan).permit(:question1, :question2, :question3, :question4)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Old+Mincho&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>

   <h1>広島のお酒</h1>
   <div class="header-list">
    <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>
 
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :お酒の名前 %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.label :お酒の詳細 %>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/index.html.erb
<h3>一覧ページ</h3>
<%= link_to "診断を始める", new_sindan_path, class: "link" %>

<% if user_signed_in? %>
  <% if current_user == @user || current_user.admin? %>
    <%= link_to "新規投稿へ", new_post_path %>
  <% end %>
<% end %>
<div class="posts-introduce">

</div>
<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="posts">
    <div class="posts-image">
    
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    </div>

    <div class="posts-name">
      <%= t.name %>
      </div>


      <div class="posts-about">

      <%= t.about %>
      </div>
      <div>
    <h2>総合評価：
    <span class="star-rating">
       <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
       <span class="star-rating-back">★★★★★</span>
    </span> 
    </h2>
    </div>
    
    <!--- 総合評価の星の部分終わり------->
    
    
    <!--- 授業レベルの星の部分 ------------>
    <div>
    <h2>飲みやすさ：
    <span class="star-rating">
       <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
       <span class="star-rating-back">★★★★★</span>
    </span>
    </h2>
    </div>
    <!--- 授業レベルの星の部分終わり-------->
    

      <%= link_to "詳細へ", post_path(t.id) %> 
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %> 
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>(広島のお酒)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @post do |f| %>


  <div class="field">
    <%= f.label :お酒の名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :詳細 %>
    <%= f.text_field :about, :size => 30 %>
  </div>
  
    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <h5>総合評価</h5>
     <div class="post_form">
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text"></span>★</label>
    
        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text"></span>★</label>
    
        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text"></span>★</label>
    
        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text"></span>★</label>
    
        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text"></span>★</label>
     </div>
<!--- 総合評価の星の部分終わり------->


<!--- 授業レベルの星の部分 ------------>
    <h5>飲みやすさ</h5>
     <div class="post_form">
        <%= f.radio_button :level,  5 ,id: 'star6'%>
        <label for="star6"><span class="text"></span>★</label>
    
        <%= f.radio_button :level,  4 ,id: 'star7'%>
        <label for="star7"><span class="text"></span>★</label>
    
        <%= f.radio_button :level, 3 ,id: 'star8'%>
        <label for="star8"><span class="text"></span>★</label>
    
        <%= f.radio_button :level , 2 ,id: 'star9'%>
        <label for="star9"><span class="text"></span>★</label>
    
        <%= f.radio_button :level , 1 ,id: 'star10'%>
        <label for="star10"><span class="text"></span>★</label>
     </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1>広島のお酒</h1>
<h3>お酒の詳細</h3>
<div class="post">
  <p><%= @post.name %></p>
  <p><%= @post.about %></p>
  <p><%= @post.created_at %></p>
</div>
<%= link_to "編集する", edit_post_path(@post.id) %>
<%= link_to "お酒一覧に戻る", posts_path %>

app/views/sindans/index.html.erb
<h1>広島のお酒診断スタート</h1>
<%= link_to "診断を始める", new_sindan_path, class: "link" %>

app/views/sindans/new.html.erb
<%= form_for(@sindan, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="sindan-container">
        <div class="col-12">
            <p>Q1. どちらかと言うと…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">じっくり考える方だ</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">考えるより行動する方だ</label>
        </div>
        <div class="col-12">
            <p>Q2. 自分の価値観として近い方は…</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">周りの人と違う存在でありたい</label>
            <%= f.radio_button :question2, "2", id: "custom_id4" %>
            <label for="custom_id4">周りと同じでいたい</label>
        </div>   
        <div class="col-12">
            <p>Q3. 人と接するときは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">相手の話をよく聞く方だ</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">自分の話をよくする方だ</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 大切にしたいのは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">論理性だ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">情緒だ</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>

app/views/sindans/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの香りは…</p>
</div>
<div class="sindan-container">
  <% case [@sindan.question1, @sindan.question2, @sindan.question3, @sindan.question4] %>
  <% when ["1", "1", "1", "1"] %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
  <% when ["1", "1", "1", "2"] %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>
  <% when ["1", "1", "2", "1"] %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>
  <% when ["1", "1", "2", "2"] %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>
  <% when ["1", "2", "1", "1"] %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>
  <% when ["1", "2", "1", "2"] %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>
  <% when ["1", "2", "2", "1"] %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>
  <% when ["1", "2", "2", "2"] %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  <% when ["2", "1", "1", "1"] %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>
  <% when ["2", "1", "1", "2"] %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>
  <% when ["2", "1", "2", "1"] %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>
  <% when ["2", "1", "2", "2"] %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>
  <% when ["2", "2", "1", "1"] %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>
  <% when ["2", "2", "1", "2"] %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>
  <% when ["2", "2", "2", "1"] %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>
  <% when ["2", "2", "2", "2"] %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>